Repository newrelic/node-newrelic-aws-sdk, pull requests merged in 2019-10, with the labels that each got.

#16 Bumping Travis to Node 12
  .travis.yml
Labels: ready for review

#17 NODE-2185 Drop Node 6 support
  .travis.yml
  package.json
Labels: ready for review, risk:low, semver:major

#18 Release v1.0.0.
  CHANGELOG.md
Labels: ready for review, risk:low, semver:major

#19 Adds additional items to npmignore to reduce chance of deployed cruft.
  .npmignore
Labels: ready for review, risk:low, semver:patch

#20 Bumps minimum versioned node engine to 8.
  tests/versioned/package.json
Labels: ready for review, risk:low, semver:patch

#22 Limits versioned tests to one older version and then newer versions going forward
  tests/versioned/package.json
Labels: ready for review, risk:low, semver:patch
