Repository newrelic/node-newrelic-aws-sdk, pull requests merged in 2019-02, with the labels that each got.

#2 NODE-1956 Instrument S3
  lib/core.js
  tests/versioned/common.js
  tests/versioned/package.json
  tests/versioned/s3.tap.js
Labels: ready for review, risk:low, semver:minor

#4 Added aws.service and aws.region attributes
  lib/core.js
  tests/versioned/common.js
  tests/versioned/s3.tap.js
Labels: ready for review, risk:low, semver:minor

#3 NODE-1957 Instrument DynamoDB
  lib/dynamodb.js
  lib/instrumentation.js
  package.json
  tests/versioned/common.js
  tests/versioned/dynamodb.tap.js
  tests/versioned/package.json
  tests/versioned/s3.tap.js
Labels: ready for review, risk:low, semver:minor

#7 update DynamoDB tests
  tests/versioned/dynamodb.tap.js
Labels: ready for review, risk:low, semver:patch

#5 Added tests for all http-based services
  tests/versioned/common.js
  tests/versioned/http-services.tap.js
  tests/versioned/package.json
  tests/versioned/s3.tap.js
Labels: ready for review, risk:low, semver:patch

#8 Updated to segment.addAttribute
  lib/core.js
  package.json
  tests/versioned/common.js
  tests/versioned/dynamodb.tap.js
  tests/versioned/http-services.tap.js
  tests/versioned/s3.tap.js
Labels: ready for review, risk:low, semver:patch

#9 Updated changelog for v0.1.0
  CHANGELOG.md
Labels: ready for review, risk:low, semver:minor

#10 NODE-1960 add SNS outbound instrumentation
  lib/dynamodb.js
  lib/instrumentation.js
  lib/sns.js
  tests/versioned/sns.tap.js
Labels: ready for review, risk:low, semver:minor

#6 NODE-1959 Adds initial instrumentation for SQS
  .gitignore
  lib/instrumentation.js
  lib/sqs.js
  package.json
  tests/versioned/common.js
  tests/versioned/sqs.tap.js
Labels: ready for review, risk:low, semver:minor

#11 Release v0.2.0
  CHANGELOG.md
Labels: risk:low, semver:minor

#12 dynamodb: move name prop to segment description root
  lib/dynamodb.js
  tests/versioned/dynamodb.tap.js
Labels: ready for review, risk:low, semver:patch
