Repository newrelic/node-newrelic-aws-sdk, pull requests merged in 2020-07, with the labels that each got.

#50 Updated README
  README.md
Labels: ready for review, risk:none, semver:patch

#48 Added GitHub PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for review

#51 #40 Updates Code of Conduct
  CODE_OF_CONDUCT.md
Labels: risk:low, semver:patch

#53 #45 Copyright to All Source Files
  index.js
  lib/core.js
  lib/dynamodb.js
  lib/instrumentation-helper.js
  lib/instrumentation.js
  lib/sns.js
  lib/sqs.js
  lib/util.js
  nr-hooks.js
  tests/unit/util.tap.js
  tests/versioned/amazon-dax-client.tap.js
  tests/versioned/aws-sdk.tap.js
  tests/versioned/common.js
  tests/versioned/dynamodb.tap.js
  tests/versioned/http-services.tap.js
  tests/versioned/instrumentation-supported.tap.js
  tests/versioned/instrumentation-unsupported.tap.js
  tests/versioned/newrelic.js
  tests/versioned/s3.tap.js
  tests/versioned/sns.tap.js
  tests/versioned/sqs.tap.js
Labels: risk:low, semver:patch

#52 #41 Adds Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/troubleshooting.md
Labels: risk:low, semver:patch

#55 update readme
  README.md
Labels: ready for review, risk:none, semver:patch

#56 Issue #54: Bumping Test Utils Dependency
  package.json
Labels: risk:low, semver:patch

#58 Updates contributing guidelines
  CONTRIBUTING.md
Labels: ready for review, risk:none, semver:patch

#60 Update third party notices and bump newrelic dependency
  THIRD_PARTY_NOTICES.md
  package.json
  third_party_manifest.json
Labels: ready for review, risk:none, semver:major

#64 Update license
  LICENSE
  package.json
Labels: risk:low, semver:patch

#63 Adds footer to third party notices
  THIRD_PARTY_NOTICES.md
Labels: risk:none, semver:patch

#61 Adds new README.md based on Current Template
  README.md
Labels: risk:low, semver:patch

#65 Remove AWS servers as dependency for versioned tests
  tests/versioned/amazon-dax-client.tap.js
  tests/versioned/aws-sdk.tap.js
  tests/versioned/aws-server-stubs/empty-response-server/index.js
  tests/versioned/aws-server-stubs/index.js
  tests/versioned/aws-server-stubs/sqs-server/index.js
  tests/versioned/aws-server-stubs/sqs-server/responses/create-queue-response.xml
  tests/versioned/aws-server-stubs/sqs-server/responses/receive-message-response.xml
  tests/versioned/aws-server-stubs/sqs-server/responses/send-message-batch-response.xml
  tests/versioned/aws-server-stubs/sqs-server/responses/send-message-response.xml
  tests/versioned/common.js
  tests/versioned/dynamodb.tap.js
  tests/versioned/http-services.tap.js
  tests/versioned/package.json
  tests/versioned/s3.tap.js
  tests/versioned/sns.tap.js
  tests/versioned/sqs.tap.js
Labels: risk:low, semver:patch

#68 Merge OS main into main
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/troubleshooting.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  THIRD_PARTY_NOTICES.md
  index.js
  lib/core.js
  lib/dynamodb.js
  lib/instrumentation-helper.js
  lib/instrumentation.js
  lib/sns.js
  lib/sqs.js
  lib/util.js
  nr-hooks.js
  package.json
  tests/unit/util.tap.js
  tests/versioned/amazon-dax-client.tap.js
  tests/versioned/aws-sdk.tap.js
  tests/versioned/aws-server-stubs/empty-response-server/index.js
  tests/versioned/aws-server-stubs/index.js
  tests/versioned/aws-server-stubs/sqs-server/index.js
  tests/versioned/aws-server-stubs/sqs-server/responses/create-queue-response.xml
  tests/versioned/aws-server-stubs/sqs-server/responses/receive-message-response.xml
  tests/versioned/aws-server-stubs/sqs-server/responses/send-message-batch-response.xml
  tests/versioned/aws-server-stubs/sqs-server/responses/send-message-response.xml
  tests/versioned/common.js
  tests/versioned/dynamodb.tap.js
  tests/versioned/http-services.tap.js
  tests/versioned/instrumentation-supported.tap.js
  tests/versioned/instrumentation-unsupported.tap.js
  tests/versioned/newrelic.js
  tests/versioned/package.json
  tests/versioned/s3.tap.js
  tests/versioned/sns.tap.js
  tests/versioned/sqs.tap.js
  third_party_manifest.json
Labels: risk:low, semver:major

#69 Adds GitHub Actions CI. Removes Travis.
  .github/workflows/ci-workflow.yml
  .travis.yml
Labels: risk:low, semver:patch

#71 Adds additional items to .npmignore.
  .npmignore
Labels: risk:low, semver:patch

#72 Readme updates to update CI badge and other items.
  README.md
Labels: risk:low, semver:patch

#73 Fixes first-line indentation of license file.
  LICENSE
Labels: risk:none, semver:patch
